# -*- coding: utf-8 -*-
"""Actividad2Juan Reales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cuqqp2QZMOVnrRUccqqVOh42dh-KnvLU
"""

import math

class persona:
  def __init__(self, nombre, apellido):
    'init método constructor para la clase persona'
    'instancias de atributo: nombre y apellido'
    self.nombre = nombre
    self.apellido= apellido
  
  def saludo(self):
    print(f"Bienvenido Sr. (self.nombre )(self.apellido)")

p1 = persona("John","Cabrera")
print(p1.nombre)
print(p1.apellido)

class compleja:

  def __init__(self,Re,Im):
    'Método constructor de la clase compleja'
    'Instancias de atributo de un número complejo: parte real e imaginaria'
    self.Re = Re
    self.Im = Im
  
  def suma(self,other):
    'Se suman las partes reales entre sí y las partes imaginarias , resultando en la forma Re + Imi'
    self.Re +  other.Re
    self.Im + other.Im
    return str(self.Re+ other.Re) +str("+") + str(self.Im + other.Im)+"i"

  def resta(self,other):
    'Se restas las partes reales entre sí y las partes imaginarias , resultando en la forma Re - Imi'
    self.Re - other.Re
    self.Im - other.Im
    return str(self.Re- other.Re) +str("+") + str(self.Im - other.Im)+"i"
    
  def producto(self,other):
    'Se aplica ley distributiva y luego sumatoria de semesjantes'
    real = (self.Re *other.Re)-(self.Im*other.Im)
    imaginaria = (self.Re*other.Im + self.Im*other.Re)
    return f"{real}+{imaginaria}i"
  

  def cociente(self,other):
    real = (self.Re*other.Re + self.Im*other.Im)/((other.Re**2)*(other.Im**2))
    imaginaria = ((self.Im*other.Re)-(self.Re*other.Im))/((other.Re**2)*(other.Im**2))
    return f"{real}+{imaginaria}i"
  
  def norma(self):
    'Raíz de la suma de los cuadrados de los coeficientes de la parte real e imaginaria de un número complejo'
    return ((self.Re**2)+(self.Im**2))**0.5

"Ejemplos de sumatoria"
z1 = compleja(2,1) # 2+i
z2 = compleja(2,2) #2+2i
z3 = compleja(4,5) # 4+5i
z4 = compleja(0,-3) #0-3i
print(z1.suma(z2))
print(z1.suma(z3))

"Ejemplos de resta"
print(z1.resta(z2))
print(z1.resta(z3))

"Ejemplos de producto"
print(z1.producto(z2))
print(z1.producto(z3))

"Ejemplos de cociente"
print(z1.cociente(z2))
print(z1.cociente(z3))

"Ejemplos de la norma"
print(z4.norma())